//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.ServiceTopshelfReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServiceTopshelf", ConfigurationName="ServiceTopshelfReference.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Add", ReplyAction="http://ServiceTopshelf/ICalculator/AddResponse")]
        double Add(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Add", ReplyAction="http://ServiceTopshelf/ICalculator/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Subtract", ReplyAction="http://ServiceTopshelf/ICalculator/SubtractResponse")]
        double Subtract(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Subtract", ReplyAction="http://ServiceTopshelf/ICalculator/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Multiply", ReplyAction="http://ServiceTopshelf/ICalculator/MultiplyResponse")]
        double Multiply(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Multiply", ReplyAction="http://ServiceTopshelf/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Divide", ReplyAction="http://ServiceTopshelf/ICalculator/DivideResponse")]
        double Divide(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/Divide", ReplyAction="http://ServiceTopshelf/ICalculator/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/DoStackOverflow", ReplyAction="http://ServiceTopshelf/ICalculator/DoStackOverflowResponse")]
        void DoStackOverflow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/DoStackOverflow", ReplyAction="http://ServiceTopshelf/ICalculator/DoStackOverflowResponse")]
        System.Threading.Tasks.Task DoStackOverflowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/DoAnyExeption", ReplyAction="http://ServiceTopshelf/ICalculator/DoAnyExeptionResponse")]
        void DoAnyExeption();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceTopshelf/ICalculator/DoAnyExeption", ReplyAction="http://ServiceTopshelf/ICalculator/DoAnyExeptionResponse")]
        System.Threading.Tasks.Task DoAnyExeptionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : ServiceClient.ServiceTopshelfReference.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<ServiceClient.ServiceTopshelfReference.ICalculator>, ServiceClient.ServiceTopshelfReference.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double n1, double n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double n1, double n2) {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public double Subtract(double n1, double n2) {
            return base.Channel.Subtract(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2) {
            return base.Channel.SubtractAsync(n1, n2);
        }
        
        public double Multiply(double n1, double n2) {
            return base.Channel.Multiply(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2) {
            return base.Channel.MultiplyAsync(n1, n2);
        }
        
        public double Divide(double n1, double n2) {
            return base.Channel.Divide(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2) {
            return base.Channel.DivideAsync(n1, n2);
        }
        
        public void DoStackOverflow() {
            base.Channel.DoStackOverflow();
        }
        
        public System.Threading.Tasks.Task DoStackOverflowAsync() {
            return base.Channel.DoStackOverflowAsync();
        }
        
        public void DoAnyExeption() {
            base.Channel.DoAnyExeption();
        }
        
        public System.Threading.Tasks.Task DoAnyExeptionAsync() {
            return base.Channel.DoAnyExeptionAsync();
        }
    }
}
